Unity implementation (#53)
* Create dir setup

* Create main menu

* Remove UserSettings

* Move interpreter into class

* Update namespaces

* WIP Unity Setup

* YOINKED DAT VISUAL BASIC DEPENDENCY

* Copy interpreter into unity and setup properly

* Move and setup testing to unity

* Move intermediate models to unity

* Move Antlr folder to Unity

* sayonara interpreter

* Move Unity game files

* Update dotnet.yml

* Update dotnet.yml

* Update dotnet.yml

* Update dotnet.yml

* Update dotnet.yml

* Update dotnet.yml

* a

* Update activation.yml

* ab

* Update dotnet.yml

* Update dotnet.yml

* Update dotnet.yml

* Update dotnet.yml

* Update dotnet.yml

* Update dotnet.yml

* Update dotnet.yml

* Update dotnet.yml

* Update dotnet.yml

* Update dotnet.yml

* Update dotnet.yml

* Update dotnet.yml

* Update dotnet.yml

* Create EditMode tests

* Update .gitignore

* Update dotnet.yml

* Update dotnet.yml

* Update dotnet.yml

* Update dotnet.yml

* Update dotnet.yml

* Update dotnet.yml

* Update dotnet.yml

* Update dotnet.yml

* Update dotnet.yml

* Update dotnet.yml

* a

* a

* Update dotnet.yml

* Update dotnet.yml

* d

* Update dotnet.yml

* a

* Update MainMenu.unity

* Regain packages and update gitignore

* Update models

* Update AST Nodes

* Refactor namespaces

* Update Scripts.asmdef

* Update UnityGame

* Update TileModel.cs

* Update ScreenModel.cs

* Basic setup done

* Update setup

* Setup actually done

Co-authored-by: Christian Bager Bach Houmann <chhoumann@gmail.com>

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -1,70 +1,68 @@
-name: .NET
-
+name: Actions 😎
 on:
-  push:
-    branches: [ main ]
+  push: { branches: [main] }
   pull_request:
-    branches: [ main ]
+    paths-ignore:
+      - '.github/**'
+
+env:
+  UNITY_LICENSE: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><root>\n    <License id=\"Terms\">\n        <MachineBindings>\n            <Binding Key=\"1\" Value=\"576562626572264761624c65526f7578\"/>\n            <Binding Key=\"2\" Value=\"576562626572264761624c65526f7578\"/>\n        </MachineBindings>\n        <MachineID Value=\"D7nTUnjNAmtsUMcnoyrqkgIbYdM=\"/>\n        <SerialHash Value=\"2033b8ac3e6faa3742ca9f0bfae44d18f2a96b80\"/>\n        <Features>\n            <Feature Value=\"33\"/>\n            <Feature Value=\"1\"/>\n            <Feature Value=\"12\"/>\n            <Feature Value=\"2\"/>\n            <Feature Value=\"24\"/>\n            <Feature Value=\"3\"/>\n            <Feature Value=\"36\"/>\n            <Feature Value=\"17\"/>\n            <Feature Value=\"19\"/>\n            <Feature Value=\"62\"/>\n        </Features>\n        <DeveloperData Value=\"AQAAAEY0LUJHUlgtWEQ0RS1aQ1dWLUM1SlctR0RIQg==\"/>\n        <SerialMasked Value=\"F4-BGRX-XD4E-ZCWV-C5JW-XXXX\"/>\n        <StartDate Value=\"2021-02-08T00:00:00\"/>\n        <UpdateDate Value=\"2021-02-09T00:34:57\"/>\n        <InitialActivationDate Value=\"2021-02-08T00:34:56\"/>\n        <LicenseVersion Value=\"6.x\"/>\n        <ClientProvidedVersion Value=\"2018.4.30f1\"/>\n        <AlwaysOnline Value=\"false\"/>\n        <Entitlements>\n            <Entitlement Ns=\"unity_editor\" Tag=\"UnityPersonal\" Type=\"EDITOR\" ValidTo=\"9999-12-31T00:00:00\"/>\n            <Entitlement Ns=\"unity_editor\" Tag=\"DarkSkin\" Type=\"EDITOR_FEATURE\" ValidTo=\"9999-12-31T00:00:00\"/>\n        </Entitlements>\n    </License>\n<Signature xmlns=\"http://www.w3.org/2000/09/xmldsig#\"><SignedInfo><CanonicalizationMethod Algorithm=\"http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments\"/><SignatureMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#rsa-sha1\"/><Reference URI=\"#Terms\"><Transforms><Transform Algorithm=\"http://www.w3.org/2000/09/xmldsig#enveloped-signature\"/></Transforms><DigestMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#sha1\"/><DigestValue>m0Db8UK+ktnOLJBtHybkfetpcKo=</DigestValue></Reference></SignedInfo><SignatureValue>o/pUbSQAukz7+ZYAWhnA0AJbIlyyCPL7bKVEM2lVqbrXt7cyey+umkCXamuOgsWPVUKBMkXtMH8L\n5etLmD0getWIhTGhzOnDCk+gtIPfL4jMo9tkEuOCROQAXCci23VFscKcrkB+3X6h4wEOtA2APhOY\nB+wvC794o8/82ffjP79aVAi57rp3Wmzx+9pe9yMwoJuljAy2sc2tIMgdQGWVmOGBpQm3JqsidyzI\nJWG2kjnc7pDXK9pwYzXoKiqUqqrut90d+kQqRyv7MSZXR50HFqD/LI69h68b7P8Bjo3bPXOhNXGR\n9YCoemH6EkfCJxp2gIjzjWW+l2Hj2EsFQi8YXw==</SignatureValue></Signature></root>"
 
 jobs:
-  test:
+  tests:
+    name: Tests
     runs-on: ubuntu-latest
-    env:
-      config: 'Release'
-      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
-
     steps:
-    - uses: actions/checkout@v2
-    - name: Setup .NET Core
-      uses: actions/setup-dotnet@v1
-      with:
-        dotnet-version: 3.1.x
+      - uses: actions/checkout@v2
+      #- uses: actions/setup-node@v2
+      #  with:
+      #    node-version: 12.x
+      #- run: yarn
+      #- run: yarn lint
+      #- run: yarn test
+      #- run: yarn build || { echo "build command should always succeed" ; exit 61; }
+      #- run: yarn build --quiet && git diff --quiet action || { echo "ERROR - index.js is different from repository version. Forgot to run `yarn build`?" ; exit 62; }
 
-      # restore dependencies  
-    - name: Install dependencies
-      working-directory: ./Code/Interpreter
-      run: dotnet restore
+  testAllModesLikeInTheReadme:
+    name: Test in ${{ matrix.testMode }} on version ${{ matrix.unityVersion }}
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        projectPath:
+          - Code/Adventure-Map-Generator
+        unityVersion:
+          - 2021.1.5f1
+        testMode:
+          - playmode
+          - editmode
+    steps:
+      ###########################
+      #         Checkout        #
+      ###########################
+      - name: Checkout
+        uses: actions/checkout@v2
+        with:
+          lfs: true
 
-      # build project
-    - name: Build
-      working-directory: ./Code/Interpreter
-      run: dotnet build --configuration $config --no-restore
-
-    - name: set pr build number (if pr)
-      id: PRNUMBER
-      if: ${{ github.event_name == 'pull_request' }}
-      uses: kkak10/pr-number-action@v1.3
-
-      # set report file and title 
-    - name: Set Test Title
-      run: | 
-            if github.event_name == 'pull_request';
-            then
-              echo "::set-env name=title::Test Run for PR #${{steps.PRNUMBER.outputs.pr}} (${{github.run_number}})"
-              echo "::set-env name=file_name::TestReport.${{steps.PRNUMBER.outputs.pr}}.${{github.run_number}}.md"
-            else
-              echo "::set-env name=title::Test Run ${{github.run_number}}"
-              echo "::set-env name=file_name::TestReport.${{github.run_number}}.md"
-            fi
-              
-       # run tests with built project
-    - name: Test PR      
-      working-directory: ./Code/Interpreter
-      run: dotnet test --no-restore --no-build --configuration $config --logger:"liquid.md;LogFileName=${{github.workspace}}/${{env.file_name}};Title=${{env.title}};"
-
-      # upload report as build artifact
-    - name: Upload a Build Artifact
-      uses: actions/upload-artifact@v2
-      if: ${{always()}}
-      with:
-        name: 'Test Run'
-        path: ${{github.workspace}}/${{env.file_name}}
-
-      # add report as PR comment (if PR)
-    - name: comment PR
-      uses: machine-learning-apps/pr-comment@master
-      if: ${{ github.event_name == 'pull_request' }}
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      with:
-        path: ${{env.file_name}}
+      ###########################
+      #          Cache          #
+      ###########################
+      - uses: actions/cache@v2
+        with:
+          path: ${{ matrix.projectPath }}/Library
+          key: Library-${{ matrix.projectPath }}
+          restore-keys: |
+            Library-
+      - uses: game-ci/unity-test-runner@v2
+        id: tests
+        with:
+          projectPath: ${{ matrix.projectPath }}
+          unityVersion: ${{ matrix.unityVersion }}
+          testMode: ${{ matrix.testMode }}
+          artifactsPath: ${{ matrix.testMode }}-artifacts
+      - uses: actions/upload-artifact@v2
+        with:
+          name: Test results for ${{ matrix.testMode }}
+          path: ${{ steps.tests.outputs.artifactsPath }}
+          retention-days: 14
